name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    name: Auto-merge dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Fetch PR details
      id: pr-details
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          
          console.log('PR Title:', pr.title);
          console.log('PR Body:', pr.body);
          
          // Check if this is a patch or minor update
          const isPatchMinor = /bump .+ from .+ to .+/.test(pr.title) && 
                              !/major|breaking/i.test(pr.body || '');
                              
          // Check for security updates
          const isSecurityUpdate = /security/i.test(pr.body || '') || 
                                  /security/i.test(pr.title);
          
          // Allow auto-merge for patch/minor updates and security updates
          const shouldAutoMerge = isPatchMinor || isSecurityUpdate;
          
          return {
            shouldAutoMerge,
            isPatchMinor,
            isSecurityUpdate,
            title: pr.title
          };
          
    - name: Wait for CI to complete
      if: fromJSON(steps.pr-details.outputs.result).shouldAutoMerge
      uses: actions/github-script@v7
      with:
        script: |
          const maxWaitTime = 10 * 60 * 1000; // 10 minutes
          const pollInterval = 30 * 1000; // 30 seconds
          const startTime = Date.now();
          
          console.log('Waiting for CI checks to complete...');
          
          while (Date.now() - startTime < maxWaitTime) {
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const allChecks = [...checks.check_runs, ...statuses];
            const pendingChecks = allChecks.filter(check => 
              check.status === 'queued' || 
              check.status === 'in_progress' ||
              check.state === 'pending'
            );
            
            const failedChecks = allChecks.filter(check => 
              check.conclusion === 'failure' || 
              check.state === 'failure' ||
              check.conclusion === 'cancelled'
            );
            
            if (failedChecks.length > 0) {
              console.log('❌ Some checks failed, will not auto-merge');
              core.setFailed('CI checks failed');
              return;
            }
            
            if (pendingChecks.length === 0) {
              console.log('✅ All checks completed successfully');
              return;
            }
            
            console.log(`⏳ Waiting for ${pendingChecks.length} checks to complete...`);
            await new Promise(resolve => setTimeout(resolve, pollInterval));
          }
          
          console.log('⏰ Timeout waiting for checks to complete');
          core.setFailed('Timeout waiting for CI checks');
          
    - name: Enable auto-merge
      if: fromJSON(steps.pr-details.outputs.result).shouldAutoMerge
      uses: actions/github-script@v7
      with:
        script: |
          const details = ${{ steps.pr-details.outputs.result }};
          
          try {
            await github.rest.pulls.enableAutoMerge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            });
            
            // Add a comment explaining the auto-merge
            const updateType = details.isSecurityUpdate ? 'security update' : 
                              details.isPatchMinor ? 'patch/minor update' : 'update';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🤖 **Auto-merge enabled**
              
              This ${updateType} will be automatically merged once all CI checks pass.
              
              **Merge criteria met:**
              ${details.isPatchMinor ? '✅ Patch or minor version update' : ''}
              ${details.isSecurityUpdate ? '✅ Security update' : ''}
              
              If you need to make changes or prevent auto-merge, disable auto-merge on this PR.`
            });
            
            console.log('✅ Auto-merge enabled for', details.title);
          } catch (error) {
            console.error('❌ Failed to enable auto-merge:', error.message);
            core.setFailed(error.message);
          }
          
    - name: Skip auto-merge
      if: "!fromJSON(steps.pr-details.outputs.result).shouldAutoMerge"
      uses: actions/github-script@v7
      with:
        script: |
          const details = ${{ steps.pr-details.outputs.result }};
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: `🤖 **Auto-merge skipped**
            
            This PR requires manual review because:
            - Major version update detected or breaking changes mentioned
            - Not a standard patch/minor dependency update
            
            **PR Title:** ${details.title}
            
            Please review and merge manually when ready.`
          });
          
          console.log('ℹ️ Auto-merge skipped for', details.title);